### ISSUE TITLE
Add get_value and set_value tests

### ISSUE THREAD

**Issue by mdpiper** [nhm-usgs/bmi-nays2dflood#7]
Tests were added in #5, but we should also add tests using the BMI `get_value` and `set_value` functions.

**Comment by rmcd-mscb** [comment]
Hey Mark, I've think I've got this worked out.  It was a little tricky because some vars have rind values around the ny dim.  When you get an opportunity please take a look at pull request:
https://github.com/nhm-usgs/bmi-nays2dflood/pull/9
thanks,
r

**Comment by mdpiper** [comment]
Will do! Thanks, Rich!
