### ISSUE TITLE
irf_test is failing with text config file

### ISSUE THREAD

**Issue by mdpiper** [nhm-usgs/bmi-nays2dflood#8]
When `irf_test` is run with `nays2dflood_default.cfg` (the pure text configuration file, no CGN), it fails on line 43, the second call to *update*. The abbreviated output is below:

```
(...output above...)

                   Start time:    0.0000
                     End time:  500.0000
                 Current time:    0.0000
                    Time step:    0.0100
                   Time units: hrs
Update one time step
                   Start time:    0.0000
      time   q_input    h_down
     0.000    2.5000   10.0000    0.0000 out
                    Stop time:    0.0100
Running

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Segmentation fault (core dumped)
```

So the first call to *update* is OK, but it fails on the second.

The other cases in `irf_test` -- the pure CGN or hybrid CGN/text -- all pass.

**Comment by rmcd-mscb** [comment]
Fixed seg fault in irf_test, changes lie in the nays2dflood repo
